-- MySQL initialization script for AI Psychological Assistant System.
-- Target: MySQL 8.x

CREATE DATABASE IF NOT EXISTS ai_psychological_assistant
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE ai_psychological_assistant;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS emotion_diary;
DROP TABLE IF EXISTS psychological_chat_message;
DROP TABLE IF EXISTS psychological_chat_session;
DROP TABLE IF EXISTS file_resource;
DROP TABLE IF EXISTS knowledge_article;
DROP TABLE IF EXISTS knowledge_category;
DROP TABLE IF EXISTS sys_user;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE sys_user (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'User ID',
  username VARCHAR(64) NOT NULL COMMENT 'Login username',
  password_hash VARCHAR(255) NOT NULL COMMENT 'Password hash, generated by backend',
  nickname VARCHAR(64) NOT NULL COMMENT 'Display name',
  avatar_url VARCHAR(512) DEFAULT NULL COMMENT 'Avatar URL',
  email VARCHAR(128) DEFAULT NULL COMMENT 'Email',
  phone VARCHAR(32) DEFAULT NULL COMMENT 'Phone number',
  role VARCHAR(32) NOT NULL DEFAULT 'USER' COMMENT 'ADMIN or USER',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '1 enabled, 0 disabled',
  last_login_at DATETIME DEFAULT NULL COMMENT 'Last login time',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0 normal, 1 deleted',
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_user_username (username),
  KEY idx_sys_user_role_status (role, status),
  KEY idx_sys_user_deleted_created_at (deleted, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='System users';

CREATE TABLE knowledge_category (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Category ID',
  parent_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'Parent category ID',
  name VARCHAR(80) NOT NULL COMMENT 'Category name',
  code VARCHAR(80) DEFAULT NULL COMMENT 'Category code',
  description VARCHAR(255) DEFAULT NULL COMMENT 'Category description',
  sort_order INT NOT NULL DEFAULT 0 COMMENT 'Sort order',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '1 enabled, 0 disabled',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0 normal, 1 deleted',
  PRIMARY KEY (id),
  UNIQUE KEY uk_knowledge_category_code (code),
  KEY idx_knowledge_category_parent_sort (parent_id, sort_order),
  KEY idx_knowledge_category_status_deleted (status, deleted),
  CONSTRAINT fk_knowledge_category_parent
    FOREIGN KEY (parent_id) REFERENCES knowledge_category (id)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Knowledge category tree';

CREATE TABLE knowledge_article (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Article ID',
  title VARCHAR(200) NOT NULL COMMENT 'Article title',
  category_id BIGINT UNSIGNED NOT NULL COMMENT 'Knowledge category ID',
  author_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'Author user ID',
  author_name VARCHAR(64) DEFAULT NULL COMMENT 'Author display name',
  summary VARCHAR(1000) DEFAULT NULL COMMENT 'Article summary',
  content MEDIUMTEXT NOT NULL COMMENT 'Rich text content',
  cover_img VARCHAR(512) DEFAULT NULL COMMENT 'Cover image path',
  tags VARCHAR(500) DEFAULT NULL COMMENT 'Comma separated tags',
  status TINYINT NOT NULL DEFAULT 0 COMMENT '0 draft, 1 published, 2 offline',
  read_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Read count',
  published_at DATETIME DEFAULT NULL COMMENT 'Published time',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0 normal, 1 deleted',
  PRIMARY KEY (id),
  KEY idx_knowledge_article_category_status (category_id, status),
  KEY idx_knowledge_article_title (title),
  KEY idx_knowledge_article_author (author_id),
  KEY idx_knowledge_article_page (deleted, status, updated_at),
  CONSTRAINT fk_knowledge_article_category
    FOREIGN KEY (category_id) REFERENCES knowledge_category (id)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_knowledge_article_author
    FOREIGN KEY (author_id) REFERENCES sys_user (id)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Knowledge articles';

CREATE TABLE file_resource (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'File ID',
  original_name VARCHAR(255) NOT NULL COMMENT 'Original file name',
  stored_name VARCHAR(255) NOT NULL COMMENT 'Stored file name',
  file_path VARCHAR(512) NOT NULL COMMENT 'Public file path',
  file_url VARCHAR(512) DEFAULT NULL COMMENT 'Full file URL',
  mime_type VARCHAR(128) DEFAULT NULL COMMENT 'MIME type',
  file_size BIGINT UNSIGNED DEFAULT NULL COMMENT 'File size in bytes',
  business_type VARCHAR(64) NOT NULL COMMENT 'Business type, e.g. ARTICLE',
  business_id VARCHAR(64) NOT NULL COMMENT 'Business ID from upload request',
  business_field VARCHAR(64) NOT NULL COMMENT 'Business field, e.g. cover',
  uploader_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'Uploader user ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0 normal, 1 deleted',
  PRIMARY KEY (id),
  KEY idx_file_resource_business (business_type, business_id, business_field),
  KEY idx_file_resource_uploader (uploader_id),
  KEY idx_file_resource_deleted_created_at (deleted, created_at),
  CONSTRAINT fk_file_resource_uploader
    FOREIGN KEY (uploader_id) REFERENCES sys_user (id)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Uploaded file resources';

CREATE TABLE psychological_chat_session (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Session ID',
  user_id BIGINT UNSIGNED NOT NULL COMMENT 'User ID',
  user_nickname VARCHAR(64) DEFAULT NULL COMMENT 'User nickname snapshot',
  session_title VARCHAR(200) NOT NULL COMMENT 'Session title',
  last_message_content VARCHAR(1000) DEFAULT NULL COMMENT 'Last message preview',
  message_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Message count',
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Session started time',
  last_message_time DATETIME DEFAULT NULL COMMENT 'Last message time',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '1 active, 2 ended',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0 normal, 1 deleted',
  PRIMARY KEY (id),
  KEY idx_chat_session_user (user_id),
  KEY idx_chat_session_page (deleted, last_message_time),
  CONSTRAINT fk_chat_session_user
    FOREIGN KEY (user_id) REFERENCES sys_user (id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Psychological chat sessions';

CREATE TABLE psychological_chat_message (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Message ID',
  session_id BIGINT UNSIGNED NOT NULL COMMENT 'Session ID',
  sender_type TINYINT NOT NULL COMMENT '1 user, 2 AI assistant, 3 system',
  content TEXT NOT NULL COMMENT 'Message content',
  model_name VARCHAR(80) DEFAULT NULL COMMENT 'AI model name',
  prompt_tokens INT UNSIGNED DEFAULT NULL COMMENT 'Prompt tokens',
  completion_tokens INT UNSIGNED DEFAULT NULL COMMENT 'Completion tokens',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0 normal, 1 deleted',
  PRIMARY KEY (id),
  KEY idx_chat_message_session_time (session_id, created_at),
  KEY idx_chat_message_sender_type (sender_type),
  CONSTRAINT fk_chat_message_session
    FOREIGN KEY (session_id) REFERENCES psychological_chat_session (id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Psychological chat messages';

CREATE TABLE emotion_diary (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Diary ID',
  user_id BIGINT UNSIGNED NOT NULL COMMENT 'User ID',
  username VARCHAR(64) DEFAULT NULL COMMENT 'Username snapshot',
  nickname VARCHAR(64) DEFAULT NULL COMMENT 'Nickname snapshot',
  diary_date DATE NOT NULL COMMENT 'Diary date',
  mood_score TINYINT NOT NULL COMMENT 'Mood score, 0-10',
  dominant_emotion VARCHAR(32) DEFAULT NULL COMMENT 'Dominant emotion',
  sleep_quality TINYINT DEFAULT NULL COMMENT 'Sleep quality, 1-5',
  stress_level TINYINT DEFAULT NULL COMMENT 'Stress level, 1-5',
  emotion_triggers VARCHAR(500) DEFAULT NULL COMMENT 'Emotion triggers',
  diary_content TEXT DEFAULT NULL COMMENT 'Diary content',
  ai_emotion_analysis JSON DEFAULT NULL COMMENT 'AI emotion analysis result',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0 normal, 1 deleted',
  PRIMARY KEY (id),
  KEY idx_emotion_diary_user_date (user_id, diary_date),
  KEY idx_emotion_diary_mood_score (mood_score),
  KEY idx_emotion_diary_page (deleted, created_at),
  CONSTRAINT chk_emotion_diary_mood_score CHECK (mood_score BETWEEN 0 AND 10),
  CONSTRAINT chk_emotion_diary_sleep_quality CHECK (sleep_quality IS NULL OR sleep_quality BETWEEN 1 AND 5),
  CONSTRAINT chk_emotion_diary_stress_level CHECK (stress_level IS NULL OR stress_level BETWEEN 1 AND 5),
  CONSTRAINT fk_emotion_diary_user
    FOREIGN KEY (user_id) REFERENCES sys_user (id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Emotion diaries';

INSERT INTO sys_user
  (id, username, password_hash, nickname, email, phone, role, status, last_login_at)
VALUES
  (1, 'admin', '$2a$10$demo-password-hash-replace-in-backend', 'System Administrator', 'admin@example.com', '13800000000', 'ADMIN', 1, NOW()),
  (2, 'student01', '$2a$10$demo-password-hash-replace-in-backend', 'Student User', 'student01@example.com', '13900000000', 'USER', 1, NOW());

INSERT INTO knowledge_category
  (id, parent_id, name, code, description, sort_order, status)
VALUES
  (1, NULL, 'Emotion Management', 'emotion-management', 'Emotion awareness and regulation', 10, 1),
  (2, NULL, 'Stress Relief', 'stress-relief', 'Stress relief methods and self help', 20, 1),
  (3, NULL, 'Interpersonal Relationship', 'relationship', 'Relationship and communication guidance', 30, 1),
  (4, 1, 'Anxiety', 'anxiety', 'Anxiety recognition and coping', 11, 1),
  (5, 1, 'Sleep', 'sleep', 'Sleep quality and relaxation', 12, 1);

INSERT INTO knowledge_article
  (id, title, category_id, author_id, author_name, summary, content, cover_img, tags, status, read_count, published_at)
VALUES
  (1, 'How to Identify Anxiety Signals', 4, 1, 'System Administrator',
   'A short guide for recognizing common anxiety signals.',
   '<p>Anxiety can appear as rapid heartbeat, tension, worry, and avoidance. Try breathing exercises and write down the trigger.</p>',
   '/uploads/articles/anxiety-cover.jpg', 'anxiety,emotion,mental health', 1, 128, NOW()),
  (2, 'Three Simple Relaxation Exercises', 2, 1, 'System Administrator',
   'Practical relaxation exercises for daily stress.',
   '<p>Use deep breathing, progressive muscle relaxation, and short mindfulness practice when pressure rises.</p>',
   '/uploads/articles/relax-cover.jpg', 'stress,relaxation,mindfulness', 1, 96, NOW()),
  (3, 'Sleep Quality Self Check', 5, 1, 'System Administrator',
   'Help users review recent sleep habits.',
   '<p>Record bedtime, wake time, night awakenings, and daytime energy to understand sleep quality.</p>',
   NULL, 'sleep,self check', 0, 12, NULL);

INSERT INTO file_resource
  (original_name, stored_name, file_path, file_url, mime_type, file_size, business_type, business_id, business_field, uploader_id)
VALUES
  ('anxiety-cover.jpg', 'anxiety-cover.jpg', '/uploads/articles/anxiety-cover.jpg', 'http://159.75.169.224:1235/uploads/articles/anxiety-cover.jpg', 'image/jpeg', 245760, 'ARTICLE', '1', 'cover', 1),
  ('relax-cover.jpg', 'relax-cover.jpg', '/uploads/articles/relax-cover.jpg', 'http://159.75.169.224:1235/uploads/articles/relax-cover.jpg', 'image/jpeg', 198240, 'ARTICLE', '2', 'cover', 1);

INSERT INTO psychological_chat_session
  (id, user_id, user_nickname, session_title, last_message_content, message_count, started_at, last_message_time, status)
VALUES
  (1, 2, 'Student User', 'Recent exam stress consultation', 'Try splitting the review task into smaller parts and reserve rest time.', 4, '2026-05-20 20:10:00', '2026-05-20 20:18:00', 2),
  (2, 2, 'Student User', 'Sleep and mood consultation', 'A stable bedtime routine can help reduce emotional fluctuation.', 2, '2026-05-22 21:30:00', '2026-05-22 21:35:00', 2);

INSERT INTO psychological_chat_message
  (session_id, sender_type, content, model_name, prompt_tokens, completion_tokens, created_at)
VALUES
  (1, 1, 'I feel nervous before the exam and cannot focus.', NULL, NULL, NULL, '2026-05-20 20:10:00'),
  (1, 2, 'It sounds like the exam pressure is affecting your attention. Let us first identify the most urgent review task.', 'psychological-assistant-demo', 120, 88, '2026-05-20 20:12:00'),
  (1, 1, 'I always worry that I cannot finish everything.', NULL, NULL, NULL, '2026-05-20 20:15:00'),
  (1, 2, 'Try splitting the review task into smaller parts and reserve rest time.', 'psychological-assistant-demo', 110, 72, '2026-05-20 20:18:00'),
  (2, 1, 'I slept late this week and my mood is unstable.', NULL, NULL, NULL, '2026-05-22 21:30:00'),
  (2, 2, 'A stable bedtime routine can help reduce emotional fluctuation.', 'psychological-assistant-demo', 98, 65, '2026-05-22 21:35:00');

INSERT INTO emotion_diary
  (id, user_id, username, nickname, diary_date, mood_score, dominant_emotion, sleep_quality, stress_level, emotion_triggers, diary_content, ai_emotion_analysis)
VALUES
  (1, 2, 'student01', 'Student User', '2026-05-20', 4, 'Anxiety', 3, 4, 'Exam preparation',
   'The exam is approaching. I feel tense and distracted.',
   JSON_OBJECT(
     'primaryEmotion', 'Anxiety',
     'emotionScore', 72,
     'riskLevel', 'Medium',
     'isNegative', true,
     'suggestion', 'Use a short review plan and include rest intervals.',
     'riskDescription', 'Sustained anxiety may affect sleep and concentration.',
     'improvementSuggestions', JSON_ARRAY('Create a 30-minute review block', 'Practice breathing before sleep', 'Seek help if symptoms persist')
   )),
  (2, 2, 'student01', 'Student User', '2026-05-22', 7, 'Calm', 4, 2, 'Finished weekly tasks',
   'Today I finished several tasks and felt more relaxed.',
   JSON_OBJECT(
     'primaryEmotion', 'Calm',
     'emotionScore', 35,
     'riskLevel', 'Low',
     'isNegative', false,
     'suggestion', 'Keep the current routine and record effective coping methods.',
     'riskDescription', 'No obvious risk in this diary.',
     'improvementSuggestions', JSON_ARRAY('Maintain sleep schedule', 'Continue journaling')
   ));

-- Smoke-test queries for interface mapping.
-- SELECT id, username, nickname, role, status FROM sys_user WHERE username = 'admin' AND deleted = 0;
-- SELECT id, parent_id, name, sort_order FROM knowledge_category WHERE deleted = 0 ORDER BY parent_id, sort_order;
-- SELECT id, title, category_id AS categoryId, author_name AS authorName, read_count AS readCount, updated_at AS updatedAt FROM knowledge_article WHERE deleted = 0 ORDER BY updated_at DESC LIMIT 10;
-- SELECT id, user_nickname AS userNickname, session_title AS sessionTitle, last_message_content AS lastMessageContent, message_count AS messageCount, last_message_time AS lastMessageTime FROM psychological_chat_session WHERE deleted = 0 ORDER BY last_message_time DESC LIMIT 10;
-- SELECT id, user_id AS userId, nickname, diary_date AS diaryDate, mood_score AS moodScore, sleep_quality AS sleepQuality, stress_level AS stressLevel, emotion_triggers AS emotionTriggers, diary_content AS diaryContent, ai_emotion_analysis AS aiEmotionAnalysis FROM emotion_diary WHERE deleted = 0 ORDER BY created_at DESC LIMIT 10;
